### ISSUE TITLE
镜像站推荐:www.paddy.ml

### ISSUE THREAD

**Issue by Paddy2333** [hmsjy2017/Google-Mirrors#2]
[www.paddy.ml](https://www.paddy.ml)为本人使用vercel搭建的谷歌反向代理站，会一直稳定运行下去，希望可以将其加入镜像站列表中

**Comment by hmsjy2017** [comment]
已于 https://github.com/hmsjy2017/Google-Mirrors/commit/f42527b93b609be90682d7d215587ea35542a0e8 添加，感谢支持
